// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"github.com/google/uuid"
	"sync"
)

// Ensure, that UserRepositoryMock does implement UserRepository.
// If this is not the case, regenerate this file with moq.
var _ UserRepository = &UserRepositoryMock{}

// UserRepositoryMock is a mock implementation of UserRepository.
//
//	func TestSomethingThatUsesUserRepository(t *testing.T) {
//
//		// make and configure a mocked UserRepository
//		mockedUserRepository := &UserRepositoryMock{
//			DeleteFunc: func(id uuid.UUID) error {
//				panic("mock out the Delete method")
//			},
//			FindByEmailFunc: func(email string) (*User, error) {
//				panic("mock out the FindByEmail method")
//			},
//			FindByIDFunc: func(id uuid.UUID) (*User, error) {
//				panic("mock out the FindByID method")
//			},
//			LoadFromVersionFunc: func(id uuid.UUID, version int) (*User, error) {
//				panic("mock out the LoadFromVersion method")
//			},
//			SaveFunc: func(user *User) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedUserRepository in code that requires UserRepository
//		// and then make assertions.
//
//	}
type UserRepositoryMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(id uuid.UUID) error

	// FindByEmailFunc mocks the FindByEmail method.
	FindByEmailFunc func(email string) (*User, error)

	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(id uuid.UUID) (*User, error)

	// LoadFromVersionFunc mocks the LoadFromVersion method.
	LoadFromVersionFunc func(id uuid.UUID, version int) (*User, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(user *User) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// ID is the id argument value.
			ID uuid.UUID
		}
		// FindByEmail holds details about calls to the FindByEmail method.
		FindByEmail []struct {
			// Email is the email argument value.
			Email string
		}
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// ID is the id argument value.
			ID uuid.UUID
		}
		// LoadFromVersion holds details about calls to the LoadFromVersion method.
		LoadFromVersion []struct {
			// ID is the id argument value.
			ID uuid.UUID
			// Version is the version argument value.
			Version int
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// User is the user argument value.
			User *User
		}
	}
	lockDelete          sync.RWMutex
	lockFindByEmail     sync.RWMutex
	lockFindByID        sync.RWMutex
	lockLoadFromVersion sync.RWMutex
	lockSave            sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *UserRepositoryMock) Delete(id uuid.UUID) error {
	if mock.DeleteFunc == nil {
		panic("UserRepositoryMock.DeleteFunc: method is nil but UserRepository.Delete was just called")
	}
	callInfo := struct {
		ID uuid.UUID
	}{
		ID: id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepository.DeleteCalls())
func (mock *UserRepositoryMock) DeleteCalls() []struct {
	ID uuid.UUID
} {
	var calls []struct {
		ID uuid.UUID
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// FindByEmail calls FindByEmailFunc.
func (mock *UserRepositoryMock) FindByEmail(email string) (*User, error) {
	if mock.FindByEmailFunc == nil {
		panic("UserRepositoryMock.FindByEmailFunc: method is nil but UserRepository.FindByEmail was just called")
	}
	callInfo := struct {
		Email string
	}{
		Email: email,
	}
	mock.lockFindByEmail.Lock()
	mock.calls.FindByEmail = append(mock.calls.FindByEmail, callInfo)
	mock.lockFindByEmail.Unlock()
	return mock.FindByEmailFunc(email)
}

// FindByEmailCalls gets all the calls that were made to FindByEmail.
// Check the length with:
//
//	len(mockedUserRepository.FindByEmailCalls())
func (mock *UserRepositoryMock) FindByEmailCalls() []struct {
	Email string
} {
	var calls []struct {
		Email string
	}
	mock.lockFindByEmail.RLock()
	calls = mock.calls.FindByEmail
	mock.lockFindByEmail.RUnlock()
	return calls
}

// FindByID calls FindByIDFunc.
func (mock *UserRepositoryMock) FindByID(id uuid.UUID) (*User, error) {
	if mock.FindByIDFunc == nil {
		panic("UserRepositoryMock.FindByIDFunc: method is nil but UserRepository.FindByID was just called")
	}
	callInfo := struct {
		ID uuid.UUID
	}{
		ID: id,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(id)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedUserRepository.FindByIDCalls())
func (mock *UserRepositoryMock) FindByIDCalls() []struct {
	ID uuid.UUID
} {
	var calls []struct {
		ID uuid.UUID
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// LoadFromVersion calls LoadFromVersionFunc.
func (mock *UserRepositoryMock) LoadFromVersion(id uuid.UUID, version int) (*User, error) {
	if mock.LoadFromVersionFunc == nil {
		panic("UserRepositoryMock.LoadFromVersionFunc: method is nil but UserRepository.LoadFromVersion was just called")
	}
	callInfo := struct {
		ID      uuid.UUID
		Version int
	}{
		ID:      id,
		Version: version,
	}
	mock.lockLoadFromVersion.Lock()
	mock.calls.LoadFromVersion = append(mock.calls.LoadFromVersion, callInfo)
	mock.lockLoadFromVersion.Unlock()
	return mock.LoadFromVersionFunc(id, version)
}

// LoadFromVersionCalls gets all the calls that were made to LoadFromVersion.
// Check the length with:
//
//	len(mockedUserRepository.LoadFromVersionCalls())
func (mock *UserRepositoryMock) LoadFromVersionCalls() []struct {
	ID      uuid.UUID
	Version int
} {
	var calls []struct {
		ID      uuid.UUID
		Version int
	}
	mock.lockLoadFromVersion.RLock()
	calls = mock.calls.LoadFromVersion
	mock.lockLoadFromVersion.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *UserRepositoryMock) Save(user *User) error {
	if mock.SaveFunc == nil {
		panic("UserRepositoryMock.SaveFunc: method is nil but UserRepository.Save was just called")
	}
	callInfo := struct {
		User *User
	}{
		User: user,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(user)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedUserRepository.SaveCalls())
func (mock *UserRepositoryMock) SaveCalls() []struct {
	User *User
} {
	var calls []struct {
		User *User
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
