openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
paths: {}
components:
  schemas:
    TestEntity:
      type: object
      x-aggregate: true
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string