openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
  description: A minimal API example for getting started with Pericarp CLI
paths: {}
components:
  schemas:
    Product:
      type: object
      required:
        - name
        - price
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the product
        name:
          type: string
          minLength: 1
          maxLength: 100
          description: Product name
        description:
          type: string
          maxLength: 500
          description: Product description
        price:
          type: number
          minimum: 0
          description: Product price in USD
        inStock:
          type: boolean
          default: true
          description: Whether the product is in stock
        category:
          type: string
          enum: [electronics, clothing, books, home, sports]
          description: Product category