// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/akeemphilbert/pericarp/pkg/domain"
	"sync"
)

// Ensure, that AggregateRootMock does implement domain.AggregateRoot.
// If this is not the case, regenerate this file with moq.
var _ domain.AggregateRoot = &AggregateRootMock{}

// AggregateRootMock is a mock implementation of domain.AggregateRoot.
//
//	func TestSomethingThatUsesAggregateRoot(t *testing.T) {
//
//		// make and configure a mocked domain.AggregateRoot
//		mockedAggregateRoot := &AggregateRootMock{
//			IDFunc: func() string {
//				panic("mock out the GetID method")
//			},
//			LoadFromHistoryFunc: func(events []domain.Event)  {
//				panic("mock out the LoadFromHistory method")
//			},
//			MarkEventsAsCommittedFunc: func()  {
//				panic("mock out the MarkEventsAsCommitted method")
//			},
//			SequenceNoFunc: func() int64 {
//				panic("mock out the GetSequenceNo method")
//			},
//			UncommittedEventsFunc: func() []domain.Event {
//				panic("mock out the UncommittedEvents method")
//			},
//		}
//
//		// use mockedAggregateRoot in code that requires domain.AggregateRoot
//		// and then make assertions.
//
//	}
type AggregateRootMock struct {
	// IDFunc mocks the ID method.
	IDFunc func() string

	// LoadFromHistoryFunc mocks the LoadFromHistory method.
	LoadFromHistoryFunc func(events []domain.Event)

	// MarkEventsAsCommittedFunc mocks the MarkEventsAsCommitted method.
	MarkEventsAsCommittedFunc func()

	// SequenceNoFunc mocks the SequenceNo method.
	SequenceNoFunc func() int64

	// UncommittedEventsFunc mocks the UncommittedEvents method.
	UncommittedEventsFunc func() []domain.Event

	// calls tracks calls to the methods.
	calls struct {
		// ID holds details about calls to the ID method.
		ID []struct {
		}
		// LoadFromHistory holds details about calls to the LoadFromHistory method.
		LoadFromHistory []struct {
			// Events is the events argument value.
			Events []domain.Event
		}
		// MarkEventsAsCommitted holds details about calls to the MarkEventsAsCommitted method.
		MarkEventsAsCommitted []struct {
		}
		// SequenceNo holds details about calls to the SequenceNo method.
		SequenceNo []struct {
		}
		// UncommittedEvents holds details about calls to the UncommittedEvents method.
		UncommittedEvents []struct {
		}
	}
	lockID                    sync.RWMutex
	lockLoadFromHistory       sync.RWMutex
	lockMarkEventsAsCommitted sync.RWMutex
	lockSequenceNo            sync.RWMutex
	lockUncommittedEvents     sync.RWMutex
}

// ID calls IDFunc.
func (mock *AggregateRootMock) ID() string {
	if mock.IDFunc == nil {
		panic("AggregateRootMock.IDFunc: method is nil but AggregateRoot.GetID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockID.Lock()
	mock.calls.ID = append(mock.calls.ID, callInfo)
	mock.lockID.Unlock()
	return mock.IDFunc()
}

// IDCalls gets all the calls that were made to ID.
// Check the length with:
//
//	len(mockedAggregateRoot.IDCalls())
func (mock *AggregateRootMock) IDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockID.RLock()
	calls = mock.calls.ID
	mock.lockID.RUnlock()
	return calls
}

// LoadFromHistory calls LoadFromHistoryFunc.
func (mock *AggregateRootMock) LoadFromHistory(events []domain.Event) {
	if mock.LoadFromHistoryFunc == nil {
		panic("AggregateRootMock.LoadFromHistoryFunc: method is nil but AggregateRoot.LoadFromHistory was just called")
	}
	callInfo := struct {
		Events []domain.Event
	}{
		Events: events,
	}
	mock.lockLoadFromHistory.Lock()
	mock.calls.LoadFromHistory = append(mock.calls.LoadFromHistory, callInfo)
	mock.lockLoadFromHistory.Unlock()
	mock.LoadFromHistoryFunc(events)
}

// LoadFromHistoryCalls gets all the calls that were made to LoadFromHistory.
// Check the length with:
//
//	len(mockedAggregateRoot.LoadFromHistoryCalls())
func (mock *AggregateRootMock) LoadFromHistoryCalls() []struct {
	Events []domain.Event
} {
	var calls []struct {
		Events []domain.Event
	}
	mock.lockLoadFromHistory.RLock()
	calls = mock.calls.LoadFromHistory
	mock.lockLoadFromHistory.RUnlock()
	return calls
}

// MarkEventsAsCommitted calls MarkEventsAsCommittedFunc.
func (mock *AggregateRootMock) MarkEventsAsCommitted() {
	if mock.MarkEventsAsCommittedFunc == nil {
		panic("AggregateRootMock.MarkEventsAsCommittedFunc: method is nil but AggregateRoot.MarkEventsAsCommitted was just called")
	}
	callInfo := struct {
	}{}
	mock.lockMarkEventsAsCommitted.Lock()
	mock.calls.MarkEventsAsCommitted = append(mock.calls.MarkEventsAsCommitted, callInfo)
	mock.lockMarkEventsAsCommitted.Unlock()
	mock.MarkEventsAsCommittedFunc()
}

// MarkEventsAsCommittedCalls gets all the calls that were made to MarkEventsAsCommitted.
// Check the length with:
//
//	len(mockedAggregateRoot.MarkEventsAsCommittedCalls())
func (mock *AggregateRootMock) MarkEventsAsCommittedCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockMarkEventsAsCommitted.RLock()
	calls = mock.calls.MarkEventsAsCommitted
	mock.lockMarkEventsAsCommitted.RUnlock()
	return calls
}

// SequenceNo calls SequenceNoFunc.
func (mock *AggregateRootMock) SequenceNo() int64 {
	if mock.SequenceNoFunc == nil {
		panic("AggregateRootMock.SequenceNoFunc: method is nil but AggregateRoot.GetSequenceNo was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSequenceNo.Lock()
	mock.calls.SequenceNo = append(mock.calls.SequenceNo, callInfo)
	mock.lockSequenceNo.Unlock()
	return mock.SequenceNoFunc()
}

// SequenceNoCalls gets all the calls that were made to SequenceNo.
// Check the length with:
//
//	len(mockedAggregateRoot.SequenceNoCalls())
func (mock *AggregateRootMock) SequenceNoCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSequenceNo.RLock()
	calls = mock.calls.SequenceNo
	mock.lockSequenceNo.RUnlock()
	return calls
}

// UncommittedEvents calls UncommittedEventsFunc.
func (mock *AggregateRootMock) UncommittedEvents() []domain.Event {
	if mock.UncommittedEventsFunc == nil {
		panic("AggregateRootMock.UncommittedEventsFunc: method is nil but AggregateRoot.UncommittedEvents was just called")
	}
	callInfo := struct {
	}{}
	mock.lockUncommittedEvents.Lock()
	mock.calls.UncommittedEvents = append(mock.calls.UncommittedEvents, callInfo)
	mock.lockUncommittedEvents.Unlock()
	return mock.UncommittedEventsFunc()
}

// UncommittedEventsCalls gets all the calls that were made to UncommittedEvents.
// Check the length with:
//
//	len(mockedAggregateRoot.UncommittedEventsCalls())
func (mock *AggregateRootMock) UncommittedEventsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockUncommittedEvents.RLock()
	calls = mock.calls.UncommittedEvents
	mock.lockUncommittedEvents.RUnlock()
	return calls
}
