// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"context"
	"sync"
)

// Ensure, that EventStoreMock does implement EventStore.
// If this is not the case, regenerate this file with moq.
var _ EventStore = &EventStoreMock{}

// EventStoreMock is a mock implementation of EventStore.
//
//	func TestSomethingThatUsesEventStore(t *testing.T) {
//
//		// make and configure a mocked EventStore
//		mockedEventStore := &EventStoreMock{
//			LoadFunc: func(ctx context.Context, aggregateID string) ([]Envelope, error) {
//				panic("mock out the Load method")
//			},
//			LoadFromSequenceFunc: func(ctx context.Context, aggregateID string, sequenceNo int64) ([]Envelope, error) {
//				panic("mock out the LoadFromSequence method")
//			},
//			SaveFunc: func(ctx context.Context, events []Event) ([]Envelope, error) {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedEventStore in code that requires EventStore
//		// and then make assertions.
//
//	}
type EventStoreMock struct {
	// LoadFunc mocks the Load method.
	LoadFunc func(ctx context.Context, aggregateID string) ([]Envelope, error)

	// LoadFromSequenceFunc mocks the LoadFromSequence method.
	LoadFromSequenceFunc func(ctx context.Context, aggregateID string, sequenceNo int64) ([]Envelope, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, events []Event) ([]Envelope, error)

	// calls tracks calls to the methods.
	calls struct {
		// Load holds details about calls to the Load method.
		Load []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AggregateID is the aggregateID argument value.
			AggregateID string
		}
		// LoadFromSequence holds details about calls to the LoadFromSequence method.
		LoadFromSequence []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AggregateID is the aggregateID argument value.
			AggregateID string
			// SequenceNo is the sequenceNo argument value.
			SequenceNo int64
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Events is the events argument value.
			Events []Event
		}
	}
	lockLoad             sync.RWMutex
	lockLoadFromSequence sync.RWMutex
	lockSave             sync.RWMutex
}

// Load calls LoadFunc.
func (mock *EventStoreMock) Load(ctx context.Context, aggregateID string) ([]Envelope, error) {
	if mock.LoadFunc == nil {
		panic("EventStoreMock.LoadFunc: method is nil but EventStore.Load was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		AggregateID string
	}{
		Ctx:         ctx,
		AggregateID: aggregateID,
	}
	mock.lockLoad.Lock()
	mock.calls.Load = append(mock.calls.Load, callInfo)
	mock.lockLoad.Unlock()
	return mock.LoadFunc(ctx, aggregateID)
}

// LoadCalls gets all the calls that were made to Load.
// Check the length with:
//
//	len(mockedEventStore.LoadCalls())
func (mock *EventStoreMock) LoadCalls() []struct {
	Ctx         context.Context
	AggregateID string
} {
	var calls []struct {
		Ctx         context.Context
		AggregateID string
	}
	mock.lockLoad.RLock()
	calls = mock.calls.Load
	mock.lockLoad.RUnlock()
	return calls
}

// LoadFromSequence calls LoadFromSequenceFunc.
func (mock *EventStoreMock) LoadFromSequence(ctx context.Context, aggregateID string, sequenceNo int64) ([]Envelope, error) {
	if mock.LoadFromSequenceFunc == nil {
		panic("EventStoreMock.LoadFromSequenceFunc: method is nil but EventStore.LoadFromSequence was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		AggregateID string
		SequenceNo  int64
	}{
		Ctx:         ctx,
		AggregateID: aggregateID,
		SequenceNo:  sequenceNo,
	}
	mock.lockLoadFromSequence.Lock()
	mock.calls.LoadFromSequence = append(mock.calls.LoadFromSequence, callInfo)
	mock.lockLoadFromSequence.Unlock()
	return mock.LoadFromSequenceFunc(ctx, aggregateID, sequenceNo)
}

// LoadFromSequenceCalls gets all the calls that were made to LoadFromSequence.
// Check the length with:
//
//	len(mockedEventStore.LoadFromSequenceCalls())
func (mock *EventStoreMock) LoadFromSequenceCalls() []struct {
	Ctx         context.Context
	AggregateID string
	SequenceNo  int64
} {
	var calls []struct {
		Ctx         context.Context
		AggregateID string
		SequenceNo  int64
	}
	mock.lockLoadFromSequence.RLock()
	calls = mock.calls.LoadFromSequence
	mock.lockLoadFromSequence.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *EventStoreMock) Save(ctx context.Context, events []Event) ([]Envelope, error) {
	if mock.SaveFunc == nil {
		panic("EventStoreMock.SaveFunc: method is nil but EventStore.Save was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Events []Event
	}{
		Ctx:    ctx,
		Events: events,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, events)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedEventStore.SaveCalls())
func (mock *EventStoreMock) SaveCalls() []struct {
	Ctx    context.Context
	Events []Event
} {
	var calls []struct {
		Ctx    context.Context
		Events []Event
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
