// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/akeemphilbert/pericarp/pkg/domain"
	"sync"
)

// Ensure, that EventDispatcherMock does implement domain.EventDispatcher.
// If this is not the case, regenerate this file with moq.
var _ domain.EventDispatcher = &EventDispatcherMock{}

// EventDispatcherMock is a mock implementation of domain.EventDispatcher.
//
//	func TestSomethingThatUsesEventDispatcher(t *testing.T) {
//
//		// make and configure a mocked domain.EventDispatcher
//		mockedEventDispatcher := &EventDispatcherMock{
//			DispatchFunc: func(ctx context.Context, envelopes []domain.Envelope) error {
//				panic("mock out the Dispatch method")
//			},
//			StartFunc: func() error {
//				panic("mock out the Start method")
//			},
//			SubscribeFunc: func(eventType string, handler domain.EventHandler) error {
//				panic("mock out the Subscribe method")
//			},
//		}
//
//		// use mockedEventDispatcher in code that requires domain.EventDispatcher
//		// and then make assertions.
//
//	}
type EventDispatcherMock struct {
	// DispatchFunc mocks the Dispatch method.
	DispatchFunc func(ctx context.Context, envelopes []domain.Envelope) error

	// StartFunc mocks the Start method.
	StartFunc func() error

	// SubscribeFunc mocks the Subscribe method.
	SubscribeFunc func(eventType string, handler domain.EventHandler) error

	// calls tracks calls to the methods.
	calls struct {
		// Dispatch holds details about calls to the Dispatch method.
		Dispatch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Envelopes is the envelopes argument value.
			Envelopes []domain.Envelope
		}
		// Start holds details about calls to the Start method.
		Start []struct {
		}
		// Subscribe holds details about calls to the Subscribe method.
		Subscribe []struct {
			// EventType is the eventType argument value.
			EventType string
			// Handler is the handler argument value.
			Handler domain.EventHandler
		}
	}
	lockDispatch  sync.RWMutex
	lockStart     sync.RWMutex
	lockSubscribe sync.RWMutex
}

// Dispatch calls DispatchFunc.
func (mock *EventDispatcherMock) Dispatch(ctx context.Context, envelopes []domain.Envelope) error {
	if mock.DispatchFunc == nil {
		panic("EventDispatcherMock.DispatchFunc: method is nil but EventDispatcher.Dispatch was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Envelopes []domain.Envelope
	}{
		Ctx:       ctx,
		Envelopes: envelopes,
	}
	mock.lockDispatch.Lock()
	mock.calls.Dispatch = append(mock.calls.Dispatch, callInfo)
	mock.lockDispatch.Unlock()
	return mock.DispatchFunc(ctx, envelopes)
}

// DispatchCalls gets all the calls that were made to Dispatch.
// Check the length with:
//
//	len(mockedEventDispatcher.DispatchCalls())
func (mock *EventDispatcherMock) DispatchCalls() []struct {
	Ctx       context.Context
	Envelopes []domain.Envelope
} {
	var calls []struct {
		Ctx       context.Context
		Envelopes []domain.Envelope
	}
	mock.lockDispatch.RLock()
	calls = mock.calls.Dispatch
	mock.lockDispatch.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *EventDispatcherMock) Start() error {
	if mock.StartFunc == nil {
		panic("EventDispatcherMock.StartFunc: method is nil but EventDispatcher.Start was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc()
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedEventDispatcher.StartCalls())
func (mock *EventDispatcherMock) StartCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Subscribe calls SubscribeFunc.
func (mock *EventDispatcherMock) Subscribe(eventType string, handler domain.EventHandler) error {
	if mock.SubscribeFunc == nil {
		panic("EventDispatcherMock.SubscribeFunc: method is nil but EventDispatcher.Subscribe was just called")
	}
	callInfo := struct {
		EventType string
		Handler   domain.EventHandler
	}{
		EventType: eventType,
		Handler:   handler,
	}
	mock.lockSubscribe.Lock()
	mock.calls.Subscribe = append(mock.calls.Subscribe, callInfo)
	mock.lockSubscribe.Unlock()
	return mock.SubscribeFunc(eventType, handler)
}

// SubscribeCalls gets all the calls that were made to Subscribe.
// Check the length with:
//
//	len(mockedEventDispatcher.SubscribeCalls())
func (mock *EventDispatcherMock) SubscribeCalls() []struct {
	EventType string
	Handler   domain.EventHandler
} {
	var calls []struct {
		EventType string
		Handler   domain.EventHandler
	}
	mock.lockSubscribe.RLock()
	calls = mock.calls.Subscribe
	mock.lockSubscribe.RUnlock()
	return calls
}
